app:
  services:
    user:
      host: 'user'
      enabled: false
    medication:
      host: 'medication'
      enabled: true

server:
  port: 3000

spring:
  application:
    name: gateway

  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        enabled: true
        register: false
